# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9286d11a9ced3f95f24d9ecd0dc8db01e74f5b3fbc17169e7d5d121cb8fa1fa1cc8ed8dffd01a047d4eaf3c857b8e31c7ff5ace73fa0bf5990106cca83527670

test:
  secret_key_base: 8f1941f63c434618e53bb7b96a3e42314c3d64e8676ba20fef7b5f840098e760400a6e762723acc6752c39a522dcb6687d2145be42c48cac0d0f28efd4879ac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
